- 👋 Hi, I’m @Jenni893
- 👀 I’m interested in Web Devolpment...
- 🌱 I’m currently learning How to host a website...
- 💞️ I’m looking to collaborate on Gisthub...
- 📫 How to reach me jenni45a@gmail.com...
- 😄 Pronouns: She..
- ⚡ Fun fact: The Pope can’t be an organ donor.


